# Copyright 2024 Google Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
!ruby/object:Api::Resource
name: "AppAttestConfig"
base_url: projects/{{project}}/apps/{{app_id}}/appAttestConfig
self_link: projects/{{project}}/apps/{{app_id}}/appAttestConfig
create_url: projects/{{project}}/apps/{{app_id}}/appAttestConfig?updateMask=tokenTtl
create_verb: :PATCH
update_verb: :PATCH
update_mask: true
skip_delete: true
description: |
  An app's App Attest configuration object. Note that the Team ID registered with your
  app is used as part of the validation process. Make sure your `google_firebase_apple_app` has a team_id present.
references: !ruby/object:Api::Resource::ReferenceLinks
  guides:
    "Official Documentation": "https://firebase.google.com/docs/app-check"
  api: "https://firebase.google.com/docs/reference/appcheck/rest/v1/projects.apps.appAttestConfig"
import_format:
  [
    "projects/{{project}}/apps/{{app_id}}/appAttestConfig",
    "{{project}}/{{app_id}}",
    "{{app_id}}",
  ]
examples:
  - !ruby/object:Provider::Terraform::Examples
    name: "firebase_app_check_app_attest_config_minimal"
    # Need the time_sleep resource
    pull_external: true
    primary_resource_id: "default"
    vars:
      team_id: "9987654321"
      bundle_id: "bundle.id.appattest"
    test_vars_overrides:
      # Don't add random suffix
      team_id: '"9987654321"'
    test_env_vars:
      project_id: :PROJECT_NAME
  - !ruby/object:Provider::Terraform::Examples
    name: "firebase_app_check_app_attest_config_full"
    # Need the time_sleep resource
    pull_external: true
    primary_resource_id: "default"
    vars:
      team_id: "9987654321"
      bundle_id: "bundle.id.appattest"
      token_ttl: "7200s"
    test_vars_overrides:
      # Don't add random suffix
      team_id: '"9987654321"'
      token_ttl: '"7200s"'
    test_env_vars:
      project_id: :PROJECT_NAME
parameters:
  - !ruby/object:Api::Type::String
    name: app_id
    description: |
      The ID of an
      [Apple App](https://firebase.google.com/docs/reference/firebase-management/rest/v1beta1/projects.iosApps#IosApp.FIELDS.app_id).
    required: true
    immutable: true
    url_param_only: true
properties:
  - !ruby/object:Api::Type::String
    name: name
    description: |
      The relative resource name of the App Attest configuration object
    output: true
    pattern: projects/{{project}}/apps/{{app_id}}/appAttestConfig
  - !ruby/object:Api::Type::String
    name: tokenTtl
    description: |
      Specifies the duration for which App Check tokens exchanged from App Attest artifacts will be valid.
      If unset, a default value of 1 hour is assumed. Must be between 30 minutes and 7 days, inclusive.

      A duration in seconds with up to nine fractional digits, ending with 's'. Example: "3.5s".
    default_from_api: true
