# Copyright 2024 Google Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Warning: This is a temporary file, and should not be edited directly
---
name: 'RecaptchaEnterpriseConfig'
description: |
  An app's reCAPTCHA Enterprise configuration object.
references:
  guides:
    'Official Documentation': 'https://firebase.google.com/docs/app-check'
  api: 'https://firebase.google.com/docs/reference/appcheck/rest/v1/projects.apps.recaptchaEnterpriseConfig'
docs:
base_url: 'projects/{{project}}/apps/{{app_id}}/recaptchaEnterpriseConfig'
self_link: 'projects/{{project}}/apps/{{app_id}}/recaptchaEnterpriseConfig'
create_url: 'projects/{{project}}/apps/{{app_id}}/recaptchaEnterpriseConfig?updateMask=tokenTtl,siteKey'
create_verb: 'PATCH'
update_verb: 'PATCH'
update_mask: true
skip_delete: true
import_format:
  - 'projects/{{project}}/apps/{{app_id}}/recaptchaEnterpriseConfig'
  - '{{project}}/{{app_id}}'
  - '{{app_id}}'
timeouts:
  insert_minutes: 20
  update_minutes: 20
  delete_minutes: 20
custom_code:
examples:
  - name: 'firebase_app_check_recaptcha_enterprise_config_basic'
    primary_resource_id: 'default'
    min_version: 'beta'
    vars:
      token_ttl: '7200s'
      site_key: '6LdpMXIpAAAAANkwWQPgEdjEhal7ugkH9RK9ytuw'
    test_env_vars:
      project_id: 'PROJECT_NAME'
    test_vars_overrides:
      'token_ttl': '"7200s"'
      'site_key': '"6LdpMXIpAAAAANkwWQPgEdjEhal7ugkH9RK9ytuw"'
    external_providers: ["random", "time"]
parameters:
  - name: 'app_id'
    type: String
    description: |
      The ID of an
      [Web App](https://firebase.google.com/docs/reference/firebase-management/rest/v1beta1/projects.webApps#WebApp.FIELDS.app_id).
    url_param_only: true
    required: true
    immutable: true
properties:
  - name: 'name'
    type: String
    description: |
      The relative resource name of the reCAPTCHA Enterprise configuration object
    output: true
  - name: 'tokenTtl'
    type: String
    description: |
      Specifies the duration for which App Check tokens exchanged from reCAPTCHA Enterprise artifacts will be valid.
      If unset, a default value of 1 hour is assumed. Must be between 30 minutes and 7 days, inclusive.

      A duration in seconds with up to nine fractional digits, ending with 's'. Example: "3.5s".
    default_from_api: true
  - name: 'siteKey'
    type: String
    description: |
      The score-based site key created in reCAPTCHA Enterprise used to invoke reCAPTCHA and generate the reCAPTCHA tokens for your application.

      **Important**: This is not the siteSecret (as it is in reCAPTCHA v3), but rather your score-based reCAPTCHA Enterprise site key.
    required: true
