# Copyright 2018 Google Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# These files contains code that needs to be compiled before being delivered to
# the final module tree structure:

<%
  return unless api.objects.first.__product
  version = api.version_obj_or_default(version_name)
  # Overrides have not been assembled yet.
  object_names = api.objects
                    .select { |o| !o.exclude_if_not_in_version(version) }
                    .map do |object|
                      ["gcp_#{object.__product.api_name}",
                       object.name.underscore].join('_')
                    end
-%>
<% object_names.each do |obj_name| -%>
'test/integration/targets/<%= obj_name -%>/aliases': 'templates/ansible/aliases'
'test/integration/targets/<%= obj_name -%>/defaults/main.yml': 'templates/ansible/defaults_main.yaml'
'test/integration/targets/<%= obj_name -%>/meta/main.yml': 'provider/ansible/blank_file.yaml'
<% end -%>

