# Copyright 2025 Google Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
name: InsightsConfig
description: Description
base_url: projects/{{project}}/locations/{{location}}/insightsConfigs
update_mask: true
self_link: projects/{{project}}/locations/{{location}}/insightsConfigs/{{insights_config_id}}
create_url: projects/{{project}}/locations/{{location}}/insightsConfigs?insightsConfigId={{insights_config_id}}
update_verb: PATCH
id_format: projects/{{project}}/locations/{{location}}/insightsConfigs/{{insights_config_id}}
import_format:
  - projects/{{project}}/locations/{{location}}/insightsConfigs/{{insights_config_id}}
examples:
  - !ruby/object:Provider::Terraform::Examples
    name: 'developer_connect_insights_config_basic'
    primary_resource_id: 'my_insights_config'
    vars:
      insights_config_name: 'tf_test_ic'
    test_env_vars:
      project: 'PROJECT_NAME'
      appHubApplication: 'APPHUB_APP_NAME'
autogen_async: true
async:
  operation:
    timeouts:
      insert_minutes: 20
      update_minutes: 20
      delete_minutes: 20
    base_url: '{{op_id}}'
  actions:
    - create
    - delete
    - update
  type: OpAsync
  result:
    resource_inside_response: true
  include_project: false
autogen_status: SW5zaWdodHNDb25maWc=
parameters:
  - name: location
    type: String
    description: Resource ID segment making up resource `name`. It identifies the resource within its parent collection as described in https://google.aip.dev/122.
    immutable: true
    url_param_only: true
    required: true
  - name: insightsConfigId
    type: String
    description: ID of the requesting InsightsConfig.
    immutable: true
    url_param_only: true
    required: true
properties:
  - name: appHubApplication
    type: String
    description: |-
      The name of the App Hub Application.
      Format:
      projects/{project}/locations/{location}/applications/{application}
  - name: name
    type: String
    description: |-
      Identifier. The name of the InsightsConfig.
      Format:
      projects/{project}/locations/{location}/insightsConfigs/{insightsConfig}
    output: true
  - name: updateTime
    type: String
    description: '[Output only] Update timestamp'
    output: true
  - name: artifactConfigs
    type: Array
    description: The artifact configurations of the artifacts that are deployed.
    item_type:
      type: NestedObject
      properties:
        - name: googleArtifactRegistry
          type: NestedObject
          description: Google Artifact Registry configurations.
          properties:
            - name: projectId
              type: String
              description: The host project of Artifact Registry.
              required: true
            - name: artifactRegistryPackage
              type: String
              description: The name of the artifact registry package.
              immutable: true
              required: true
        - name: googleArtifactAnalysis
          type: NestedObject
          description: Google Artifact Analysis configurations.
          properties:
            - name: projectId
              type: String
              description: The project id of the project where the provenance is stored.
              required: true
        - name: uri
          type: String
          description: |-
            The URI of the artifact that is deployed.
            e.g. `us-docker.pkg.dev/my-project/my-repo/image`.
            The URI does not include the tag / digest because it captures a lineage of
            artifacts.
          immutable: true
  - name: annotations
    type: KeyValueAnnotations
    description: |-
      User specified annotations. See https://google.aip.dev/148#annotations
      for more details such as format and size limitations.
  - name: labels
    type: KeyValueLabels
    description: Set of labels associated with an InsightsConfig.
    ignore_read: true
  - name: reconciling
    type: Boolean
    description: |-
      Reconciling (https://google.aip.dev/128#reconciliation).
      Set to true if the current state of InsightsConfig does not match the
      user's intended state, and the service is actively updating the resource to
      reconcile them. This can happen due to user-triggered updates or
      system actions like failover or maintenance.
    output: true
  - name: errors
    type: Array
    description: |-
      Any errors that occurred while setting up the InsightsConfig.
      Each error will be in the format: `field_name: error_message`, e.g.
      GetAppHubApplication: Permission denied while getting App Hub
      application. Please grant permissions to the P4SA.
    output: true
    item_type:
      type: NestedObject
      properties:
        - name: code
          type: Integer
          description: The status code, which should be an enum value of google.rpc.Code.
          output: true
        - name: message
          type: String
          description: |-
            A developer-facing error message, which should be in English. Any
            user-facing error message should be localized and sent in the
            google.rpc.Status.details field, or localized by the client.
          output: true
        - name: details
          type: Array
          description: |-
            A list of messages that carry the error details.  There is a common set of
            message types for APIs to use.
          output: true
          item_type:
            type: NestedObject
            properties:
              - name: detail_message
                type: String
                description: |-
                  A message with details about the error.
                output: true
  - name: createTime
    type: String
    description: '[Output only] Create timestamp'
    output: true
  - name: runtimeConfigs
    type: Array
    description: The runtime configurations where the application is deployed.
    output: true
    item_type:
      type: NestedObject
      properties:
        - name: uri
          type: String
          description: |-
            The URI of the runtime configuration.
            For GKE, this is the cluster name.
            For Cloud Run, this is the service name.
          immutable: true
          required: true
        - name: state
          type: String
          description: |-
            The state of the Runtime.
            Possible values:
            STATE_UNSPECIFIED
            LINKED
            UNLINKED
          output: true
        - name: gkeWorkload
          type: NestedObject
          description: GKEWorkload represents the Google Kubernetes Engine runtime.
          properties:
            - name: cluster
              type: String
              description: |-
                The name of the GKE cluster.
                Format:
                `projects/{project}/locations/{location}/clusters/{cluster}`.
              immutable: true
              required: true
            - name: deployment
              type: String
              description: |-
                The name of the GKE deployment.
                Format:
                `projects/{project}/locations/{location}/clusters/{cluster}/namespaces/{namespace}/deployments/{deployment}`.
              output: true
        - name: appHubWorkload
          type: NestedObject
          description: AppHubWorkload represents the App Hub Workload.
          properties:
            - name: criticality
              type: String
              description: The criticality of the App Hub Workload.
              output: true
            - name: environment
              type: String
              description: The environment of the App Hub Workload.
              output: true
            - name: workload
              type: String
              description: |-
                Output only. The name of the App Hub Workload.
                Format:
                `projects/{project}/locations/{location}/applications/{application}/workloads/{workload}`.
              output: true
              immutable: false
              required: false
  - name: state
    type: String
    description: |-
      The state of the InsightsConfig.
      Possible values:
      STATE_UNSPECIFIED
      PENDING
      COMPLETE
      ERROR
    output: true
