# Copyright 2020 Google Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
--- !ruby/object:Provider::Ansible::Example
dependencies:
  - !ruby/object:Provider::Ansible::Task
    name: gcp_compute_instance_group
    register: instancegroup
    code:
      name: <%= dependency_name('instanceGroup', 'targetHttpsProxy') %>
      zone: 'us-central1-a'
      project: <%= ctx[:project] %>
      auth_kind: <%= ctx[:auth_kind] %>
      service_account_file: <%= ctx[:service_account_file] %>
  - !ruby/object:Provider::Ansible::Task
    name: gcp_compute_region_health_check
    register: healthcheck
    code:
        name: <%= ctx[:name] %>
        type: HTTPS
        healthy_threshold: 10
        timeout_sec: 2
        unhealthy_threshold: 5
        region: 'us-central1'
        project: <%= ctx[:project] %>
        auth_kind: <%= ctx[:auth_kind] %>
        service_account_file: <%= ctx[:service_account_file] %>
  - !ruby/object:Provider::Ansible::Task
    name: gcp_compute_region_backend_service
    register: backendservice
    code:
      name: <%= dependency_name('backendService', 'targetHttpsProxy') %>
      region: "us-central1"
      backends:
        - group: "{{ instancegroup.selfLink }}"
      healthchecks:
        - "{{ healthcheck.selfLink }}"
      project: <%= ctx[:project] %>
      auth_kind: <%= ctx[:auth_kind] %>
      service_account_file: <%= ctx[:service_account_file] %>
  - !ruby/object:Provider::Ansible::Task
    name: gcp_compute_region_url_map
    register: urlmap
    code:
      name: <%= dependency_name('urlMap', 'targetHttpsProxy') %>
      region: "us-central1"
      default_service: "{{ backendservice }}"
      project: <%= ctx[:project] %>
      auth_kind: <%= ctx[:auth_kind] %>
      service_account_file: <%= ctx[:service_account_file] %>
  - !ruby/object:Provider::Ansible::Task
    name: gcp_compute_ssl_certificate
    register: sslcert
    code:
      name: <%= dependency_name('sslCert', 'targetHttpsProxy') %>
      description: A certificate for testing. Do not use this certificate in production
      certificate: |
        -----BEGIN CERTIFICATE-----
        MIICqjCCAk+gAwIBAgIJAIuJ+0352Kq4MAoGCCqGSM49BAMCMIGwMQswCQYDVQQG
        EwJVUzETMBEGA1UECAwKV2FzaGluZ3RvbjERMA8GA1UEBwwIS2lya2xhbmQxFTAT
        BgNVBAoMDEdvb2dsZSwgSW5jLjEeMBwGA1UECwwVR29vZ2xlIENsb3VkIFBsYXRm
        b3JtMR8wHQYDVQQDDBZ3d3cubXktc2VjdXJlLXNpdGUuY29tMSEwHwYJKoZIhvcN
        AQkBFhJuZWxzb25hQGdvb2dsZS5jb20wHhcNMTcwNjI4MDQ1NjI2WhcNMjcwNjI2
        MDQ1NjI2WjCBsDELMAkGA1UEBhMCVVMxEzARBgNVBAgMCldhc2hpbmd0b24xETAP
        BgNVBAcMCEtpcmtsYW5kMRUwEwYDVQQKDAxHb29nbGUsIEluYy4xHjAcBgNVBAsM
        FUdvb2dsZSBDbG91ZCBQbGF0Zm9ybTEfMB0GA1UEAwwWd3d3Lm15LXNlY3VyZS1z
        aXRlLmNvbTEhMB8GCSqGSIb3DQEJARYSbmVsc29uYUBnb29nbGUuY29tMFkwEwYH
        KoZIzj0CAQYIKoZIzj0DAQcDQgAEHGzpcRJ4XzfBJCCPMQeXQpTXwlblimODQCuQ
        4mzkzTv0dXyB750fOGN02HtkpBOZzzvUARTR10JQoSe2/5PIwaNQME4wHQYDVR0O
        BBYEFKIQC3A2SDpxcdfn0YLKineDNq/BMB8GA1UdIwQYMBaAFKIQC3A2SDpxcdfn
        0YLKineDNq/BMAwGA1UdEwQFMAMBAf8wCgYIKoZIzj0EAwIDSQAwRgIhALs4vy+O
        M3jcqgA4fSW/oKw6UJxp+M6a+nGMX+UJR3YgAiEAvvl39QRVAiv84hdoCuyON0lJ
        zqGNhIPGq2ULqXKK8BY=
        -----END CERTIFICATE-----
      private_key: |
        -----BEGIN EC PRIVATE KEY-----
        MHcCAQEEIObtRo8tkUqoMjeHhsOh2ouPpXCgBcP+EDxZCB/tws15oAoGCCqGSM49
        AwEHoUQDQgAEHGzpcRJ4XzfBJCCPMQeXQpTXwlblimODQCuQ4mzkzTv0dXyB750f
        OGN02HtkpBOZzzvUARTR10JQoSe2/5PIwQ==
        -----END EC PRIVATE KEY-----
      project: <%= ctx[:project] %>
      auth_kind: <%= ctx[:auth_kind] %>
      service_account_file: <%= ctx[:service_account_file] %>
task: !ruby/object:Provider::Ansible::Task
  name: gcp_compute_region_target_https_proxy
  code:
    name: <%= ctx[:name] %>
    region: "us-central1"
    ssl_certificates:
      - "{{ sslcert }}"
    url_map: "{{ urlmap }}"
    project: <%= ctx[:project] %>
    auth_kind: <%= ctx[:auth_kind] %>
    service_account_file: <%= ctx[:service_account_file] %>
