# Copyright 2024 Google Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
name: 'MuteConfig'
description: |
  Mute Findings is a volume management feature in Security Command Center
  that lets you manually or programmatically hide irrelevant findings,
  and create filters to automatically silence existing and future
  findings based on criteria you specify.
references:
  guides:
  api: 'https://cloud.google.com/security-command-center/docs/reference/rest/v1/organizations.muteConfigs'
docs:
base_url: '{{parent}}/muteConfigs'
self_link: '{{name}}'
create_url: '{{parent}}/muteConfigs?muteConfigId={{mute_config_id}}'
update_verb: 'PATCH'
update_mask: true
import_format:
  - '{{name}}'
timeouts:
  insert_minutes: 20
  update_minutes: 20
  delete_minutes: 20
custom_code:
  custom_import: 'templates/terraform/custom_import/scc_mute_config.go.tmpl'
# Skipping sweeper since this is a child resource
exclude_sweeper: true
examples:
  - name: 'scc_mute_config'
    primary_resource_id: 'default'
    vars:
      mute_config_id: 'my-config'
    test_env_vars:
      org_id: 'ORG_ID'
parameters:
  - name: 'muteConfigId'
    type: String
    description: |
      Unique identifier provided by the client within the parent scope.
    url_param_only: true
    required: true
    immutable: true
  - name: 'parent'
    type: String
    description: |
      Resource name of the new mute configs's parent. Its format is
      "organizations/[organization_id]", "folders/[folder_id]", or
      "projects/[project_id]".
    url_param_only: true
    required: true
    immutable: true
properties:
  - name: 'name'
    type: String
    description: |
      Name of the mute config. Its format is
      organizations/{organization}/muteConfigs/{configId},
      folders/{folder}/muteConfigs/{configId},
      or projects/{project}/muteConfigs/{configId}
    output: true
  - name: 'description'
    type: String
    description: A description of the mute config.
  - name: 'filter'
    type: String
    description: |
      An expression that defines the filter to apply across create/update
      events of findings. While creating a filter string, be mindful of
      the scope in which the mute configuration is being created. E.g.,
      If a filter contains project = X but is created under the
      project = Y scope, it might not match any findings.
    required: true
  - name: 'createTime'
    type: String
    description: |
      The time at which the mute config was created. This field is set by
      the server and will be ignored if provided on config creation.
    output: true
  - name: 'updateTime'
    type: String
    description: |
      Output only. The most recent time at which the mute config was
      updated. This field is set by the server and will be ignored if
      provided on config creation or update.
    output: true
  - name: 'mostRecentEditor'
    type: String
    description: |
      Email address of the user who last edited the mute config. This
      field is set by the server and will be ignored if provided on
      config creation or update.
    output: true
