# Copyright 2024 Google Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
name: 'BitbucketServerConfig'
description: |
  BitbucketServerConfig represents the configuration for a Bitbucket Server.
references:
  guides:
    'Connect to a Bitbucket Server host': 'https://cloud.google.com/build/docs/automating-builds/bitbucket/connect-host-bitbucket-server'
  api: 'https://cloud.google.com/build/docs/api/reference/rest/v1/projects.locations.bitbucketServerConfigs'
docs:
id_format: 'projects/{{project}}/locations/{{location}}/bitbucketServerConfigs/{{config_id}}'
base_url: 'projects/{{project}}/locations/{{location}}/bitbucketServerConfigs'
self_link: 'projects/{{project}}/locations/{{location}}/bitbucketServerConfigs/{{config_id}}'
create_url: 'projects/{{project}}/locations/{{location}}/bitbucketServerConfigs?bitbucketServerConfigId={{config_id}}'
update_verb: 'PATCH'
update_mask: true
import_format:
  - 'projects/{{project}}/locations/{{location}}/bitbucketServerConfigs/{{config_id}}'
timeouts:
  insert_minutes: 20
  update_minutes: 20
  delete_minutes: 20
autogen_async: true
async:
  actions: ['create', 'delete', 'update']
  type: 'OpAsync'
  operation:
    base_url: '{{op_id}}'
  result:
    resource_inside_response: true
include_in_tgc_next_DO_NOT_USE: true
custom_code:
  encoder: 'templates/terraform/encoders/cloudbuild_bitbucketserver_config.go.tmpl'
  post_create: 'templates/terraform/post_create/cloudbuild_bitbucketserver_config.go.tmpl'
  pre_update: 'templates/terraform/pre_update/cloudbuild_bitbucketserver_config.go.tmpl'
  post_update: 'templates/terraform/post_update/cloudbuild_bitbucketserver_config.go.tmpl'
examples:
  - name: 'cloudbuild_bitbucket_server_config'
    primary_resource_id: 'bbs-config'
    vars:
      config_id: 'bbs-config'
  - name: 'cloudbuild_bitbucket_server_config_repositories'
    primary_resource_id: 'bbs-config-with-repos'
    vars:
      config_id: 'bbs-config'
    exclude_test: true
  - name: 'cloudbuild_bitbucket_server_config_peered_network'
    primary_resource_id: 'bbs-config-with-peered-network'
    vars:
      config_id: 'bbs-config'
      network_name: 'vpc-network'
      global_address_name: 'private-ip-alloc'
parameters:
  - name: 'config_id'
    type: String
    description: |
      The ID to use for the BitbucketServerConfig, which will become the final component of the BitbucketServerConfig's resource name.
    url_param_only: true
    required: true
    immutable: true
  - name: 'location'
    type: String
    description: |
      The location of this bitbucket server config.
    url_param_only: true
    required: true
    immutable: true
properties:
  - name: 'name'
    type: String
    description: |
      The resource name for the config.
    output: true
  - name: 'hostUri'
    type: String
    description: |
      Immutable. The URI of the Bitbucket Server host. Once this field has been set, it cannot be changed.
      If you need to change it, please create another BitbucketServerConfig.
    required: true
  - name: 'secrets'
    type: NestedObject
    description: |
      Secret Manager secrets needed by the config.
    required: true
    properties:
      - name: 'adminAccessTokenVersionName'
        type: String
        description: |
          The resource name for the admin access token's secret version.
        required: true
      - name: 'readAccessTokenVersionName'
        type: String
        description: |
          The resource name for the read access token's secret version.
        required: true
      - name: 'webhookSecretVersionName'
        type: String
        description: |
          Immutable. The resource name for the webhook secret's secret version. Once this field has been set, it cannot be changed.
          Changing this field will result in deleting/ recreating the resource.
        required: true
        immutable: true
  - name: 'username'
    type: String
    description: |
      Username of the account Cloud Build will use on Bitbucket Server.
    required: true
  - name: 'webhookKey'
    type: String
    description: |
      Output only. UUID included in webhook requests. The UUID is used to look up the corresponding config.
    output: true
  - name: 'apiKey'
    type: String
    description: |
      Immutable. API Key that will be attached to webhook. Once this field has been set, it cannot be changed.
      Changing this field will result in deleting/ recreating the resource.
    required: true
    immutable: true
  - name: 'connectedRepositories'
    type: Array
    description: |
      Connected Bitbucket Server repositories for this config.
    is_set: true
    item_type:
      type: NestedObject
      properties:
        - name: 'projectKey'
          type: String
          description: |
            Identifier for the project storing the repository.
          required: true
        - name: 'repoSlug'
          type: String
          description: |
            Identifier for the repository.
          required: true
  - name: 'peeredNetwork'
    type: String
    description: |
      The network to be used when reaching out to the Bitbucket Server instance. The VPC network must be enabled for private service connection.
      This should be set if the Bitbucket Server instance is hosted on-premises and not reachable by public internet. If this field is left empty,
      no network peering will occur and calls to the Bitbucket Server instance will be made over the public internet. Must be in the format
      projects/{project}/global/networks/{network}, where {project} is a project number or id and {network} is the name of a VPC network in the project.
  - name: 'sslCa'
    type: String
    description: |
      SSL certificate to use for requests to Bitbucket Server. The format should be PEM format but the extension can be one of .pem, .cer, or .crt.
