# Copyright 2023 Google Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

--- !ruby/object:Api::Resource
name: 'BitbucketServerConfig'
base_url: projects/{{project}}/locations/{{location}}/bitbucketServerConfigs
self_link: projects/{{project}}/locations/{{location}}/bitbucketServerConfigs/{{config_id}}
create_url: projects/{{project}}/locations/{{location}}/bitbucketServerConfigs?bitbucketServerConfigId={{config_id}}
update_verb: :PATCH
update_mask: true
references: !ruby/object:Api::Resource::ReferenceLinks
  guides:
    'Connect to a Bitbucket Server host': 'https://cloud.google.com/build/docs/automating-builds/bitbucket/connect-host-bitbucket-server'
  api: 'https://cloud.google.com/build/docs/api/reference/rest/v1/projects.locations.bitbucketServerConfigs'
description: |
  BitbucketServerConfig represents the configuration for a Bitbucket Server.
async: !ruby/object:Api::OpAsync
  operation: !ruby/object:Api::OpAsync::Operation
    path: 'name'
    base_url: '{{op_id}}'
    wait_ms: 1000
  result: !ruby/object:Api::OpAsync::Result
    path: 'response'
    resource_inside_response: true
  status: !ruby/object:Api::OpAsync::Status
    path: 'done'
    complete: true
    allowed:
      - true
      - false
  error: !ruby/object:Api::OpAsync::Error
    path: 'error'
    message: 'message'
autogen_async: true
import_format:
  - 'projects/{{project}}/locations/{{location}}/bitbucketServerConfigs/{{config_id}}'
id_format: 'projects/{{project}}/locations/{{location}}/bitbucketServerConfigs/{{config_id}}'
examples:
  - !ruby/object:Provider::Terraform::Examples
    name: 'cloudbuild_bitbucket_server_config'
    primary_resource_id: 'bbs-config'
    vars:
      config_id: 'bbs-config'
  - !ruby/object:Provider::Terraform::Examples
    name: 'cloudbuild_bitbucket_server_config_repositories'
    primary_resource_id: 'bbs-config-with-repos'
    vars:
      config_id: 'bbs-config'
    skip_test: true
  - !ruby/object:Provider::Terraform::Examples
    name: 'cloudbuild_bitbucket_server_config_peered_network'
    primary_resource_id: 'bbs-config-with-peered-network'
    vars:
      config_id: 'bbs-config'
      network_name: 'vpc-network'
      global_address_name: 'private-ip-alloc'
    test_vars_overrides:
      network_name: 'acctest.BootstrapSharedTestNetwork(t, "peered-network")'
custom_code: !ruby/object:Provider::Terraform::CustomCode
  encoder: templates/terraform/encoders/cloudbuild_bitbucketserver_config.go.erb
  post_create: templates/terraform/post_create/cloudbuild_bitbucketserver_config.go.erb
  pre_update: templates/terraform/pre_update/cloudbuild_bitbucketserver_config.go.erb
  post_update: templates/terraform/post_update/cloudbuild_bitbucketserver_config.go.erb
parameters:
  - !ruby/object:Api::Type::String
    name: 'config_id'
    required: true
    url_param_only: true
    immutable: true
    description: |
      The ID to use for the BitbucketServerConfig, which will become the final component of the BitbucketServerConfig's resource name.
  - !ruby/object:Api::Type::String
    name: 'location'
    url_param_only: true
    immutable: true
    required: true
    description: |
      The location of this bitbucket server config.
properties:
  - !ruby/object:Api::Type::String
    name: 'name'
    output: true
    description: |
      The resource name for the config.
  - !ruby/object:Api::Type::String
    name: 'hostUri'
    required: true
    description: |
      Immutable. The URI of the Bitbucket Server host. Once this field has been set, it cannot be changed.
      If you need to change it, please create another BitbucketServerConfig.
  - !ruby/object:Api::Type::NestedObject
    name: 'secrets'
    required: true
    description: |
      Secret Manager secrets needed by the config.
    properties:
      - !ruby/object:Api::Type::String
        name: 'adminAccessTokenVersionName'
        required: true
        description: |
          The resource name for the admin access token's secret version.
      - !ruby/object:Api::Type::String
        name: 'readAccessTokenVersionName'
        required: true
        description: |
          The resource name for the read access token's secret version.
      - !ruby/object:Api::Type::String
        name: 'webhookSecretVersionName'
        required: true
        immutable: true
        description: |
          Immutable. The resource name for the webhook secret's secret version. Once this field has been set, it cannot be changed.
          Changing this field will result in deleting/ recreating the resource.
  - !ruby/object:Api::Type::String
    name: 'username'
    required: true
    description: |
      Username of the account Cloud Build will use on Bitbucket Server.
  - !ruby/object:Api::Type::String
    name: 'webhookKey'
    output: true
    description: |
      Output only. UUID included in webhook requests. The UUID is used to look up the corresponding config.
  - !ruby/object:Api::Type::String
    name: 'apiKey'
    required: true
    immutable: true
    description: |
      Immutable. API Key that will be attached to webhook. Once this field has been set, it cannot be changed.
      Changing this field will result in deleting/ recreating the resource.
  - !ruby/object:Api::Type::Array
    name: 'connectedRepositories'
    description: |
      Connected Bitbucket Server repositories for this config.
    is_set: true
    item_type: !ruby/object:Api::Type::NestedObject
      properties:
        - !ruby/object:Api::Type::String
          name: 'projectKey'
          required: true
          description: |
            Identifier for the project storing the repository.
        - !ruby/object:Api::Type::String
          name: 'repoSlug'
          required: true
          description: |
            Identifier for the repository.
  - !ruby/object:Api::Type::String
    name: 'peeredNetwork'
    description: |
      The network to be used when reaching out to the Bitbucket Server instance. The VPC network must be enabled for private service connection.
      This should be set if the Bitbucket Server instance is hosted on-premises and not reachable by public internet. If this field is left empty,
      no network peering will occur and calls to the Bitbucket Server instance will be made over the public internet. Must be in the format
      projects/{project}/global/networks/{network}, where {project} is a project number or id and {network} is the name of a VPC network in the project.
  - !ruby/object:Api::Type::String
    name: 'sslCa'
    description: |
      SSL certificate to use for requests to Bitbucket Server. The format should be PEM format but the extension can be one of .pem, .cer, or .crt.
