# Copyright 2024 Google Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

--- !ruby/object:Api::DataSource
name: 'google_kms_autokey_config'
description: 'Reads the KMS AutokeyConfig for a folder or project.'
base_url: '{{parent}}/autokeyConfig'
self_link: '{{name}}'

parameters:
  - !ruby/object:Api::Type::String
    name: 'folder'
    description: 'The folder, in the format `folders/{{folder_id}}`'
    conflicts:
      - 'project'
    url_param_only: true
    required: false
  - !ruby/object:Api::Type::String
    name: 'project'
    description: 'The project, in the format `projects/{{project_id}}`'
    conflicts:
      - 'folder'
    url_param_only: true
    required: false

properties:
  - !ruby/object:Api::Type::String
    name: 'name'
    description: 'The resource name for the `AutokeyConfig` in the format `folders/{{folder_id}}/autokeyConfig` or `projects/{{project_id}}/autokeyConfig`.'
    output: true
  - !ruby/object:Api::Type::String
    name: 'keyProject'
    api_name: keyProject
    description: 'The key project to use for this folder. This should be in the format `projects/{{project_id}}`.'
    output: true
  - !ruby/object:Api::Type::Enum
    name: 'keyProjectResolutionMode'
    api_name: keyProjectResolutionMode
    description: 'How to resolve the project used for key provisioning.'
    enum_values:
      - :KEY_PROJECT_RESOLUTION_MODE_UNSPECIFIED
      - :DEDICATED_KEY_PROJECT
      - :RESOURCE_PROJECT
      - :DISABLED
    output: true

custom_code: !ruby/object:Provider::Terraform::CustomCode
  decoder: templates/terraform/decoders/kms_autokey_config.go.erb
  # Use the same custom create template as the resource so generated provider
  # will issue PATCH for singleton AutokeyConfig creation (project-scoped).
  custom_create: templates/terraform/custom_create/kms_autokey_config.go.erb
