# Copyright 2024 Google Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
name: 'ServiceNetworkSettings'
description: |
  A NetworkSettings resource is a container for ingress settings for a version or service.
references:
  guides:
  api: 'https://cloud.google.com/appengine/docs/admin-api/reference/rest/v1/apps.services'
docs:
id_format: 'apps/{{project}}/services/{{service}}'
base_url: 'apps/{{project}}/services'
self_link: 'apps/{{project}}/services/{{service}}'
create_url: 'apps/{{project}}/services/{{service}}?updateMask=networkSettings'
create_verb: 'PATCH'
update_url: 'apps/{{project}}/services/{{service}}'
update_verb: 'PATCH'
update_mask: true
exclude_delete: true
mutex: 'apps/{{project}}'
import_format:
  - 'apps/{{project}}/services/{{service}}'
timeouts:
  insert_minutes: 20
  update_minutes: 20
  delete_minutes: 20
async:
  actions: ['create', 'delete', 'update']
  type: 'OpAsync'
  operation:
    base_url: '{{op_id}}'
    kind: 'appengine#operation'
    path: 'name'
    wait_ms: 1000
  result:
    path: 'targetLink'
    resource_inside_response: false
  error:
    path: 'error/errors'
    message: 'message'
custom_code:
  test_check_destroy: 'templates/terraform/custom_check_destroy/skip_delete_during_test.go.tmpl'
examples:
  - name: 'app_engine_service_network_settings'
    primary_resource_id: 'internalapp'
    vars:
      bucket_name: 'appengine-static-content'
parameters:
properties:
  - name: 'service'
    type: String
    description: |
      The name of the service these settings apply to.
    api_name: id
    required: true
  - name: 'networkSettings'
    type: NestedObject
    description: |
      Ingress settings for this service. Will apply to all versions.
    required: true
    properties:
      - name: 'ingressTrafficAllowed'
        type: Enum
        description: |
          The ingress settings for version or service.
        default_value: "INGRESS_TRAFFIC_ALLOWED_UNSPECIFIED"
        enum_values:
          - 'INGRESS_TRAFFIC_ALLOWED_UNSPECIFIED'
          - 'INGRESS_TRAFFIC_ALLOWED_ALL'
          - 'INGRESS_TRAFFIC_ALLOWED_INTERNAL_ONLY'
          - 'INGRESS_TRAFFIC_ALLOWED_INTERNAL_AND_LB'
