# Copyright 2023 Google Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

--- !ruby/object:Api::Resource
name: ProjectDefaultConfig
base_url: 'projects/{{project}}/config'
self_link: 'projects/{{project}}/config'
update_verb: :PATCH
update_mask: true
description: |
  There is no persistent data associated with this resource.
create_verb: :PATCH
delete_verb: :PATCH
custom_code: !ruby/object:Provider::Terraform::CustomCode
  resource_definition: 'templates/terraform/resource_definition/default_provider_values.erb'
  test_check_destroy: templates/terraform/custom_check_destroy/identity_platform_project_default_config.go.erb
docs: !ruby/object:Provider::Terraform::Docs
  warning: |
    If you are using User ADCs (Application Default Credentials) with this resource,
    you must specify a `billing_project` and set `user_project_override` to true
    in the provider configuration. Otherwise the ACM API will return a 403 error.
    Your account must have the `serviceusage.services.use` permission on the
    `billing_project` you defined.
id_format: '{{project}}'
examples:
  - !ruby/object:Provider::Terraform::Examples
    name: 'identity_platform_project_default_config'
    primary_resource_id:
      'default'
      # skip tests for this resource until we ensure other settings will not be cleared
      # see https://github.com/hashicorp/terraform-provider-google/issues/13327
    skip_test: true

properties:
  - !ruby/object:Api::Type::String
    name: 'name'
    description: |
      The name of the Config resource. Example: "projects/my-awesome-project/config"
    output: true
  - !ruby/object:Api::Type::NestedObject
    name: 'signIn'
    description: |
      Configuration related to local sign in methods.
    properties:
      - !ruby/object:Api::Type::NestedObject
        name: email
        description: |
          Configuration options related to authenticating a user by their email address.
        properties:
          - !ruby/object:Api::Type::Boolean
            name: enabled
            description: |
              Whether email auth is enabled for the project or not.
          - !ruby/object:Api::Type::Boolean
            name: 'passwordRequired'
            description: |
              Whether a password is required for email auth or not. If true, both an email and
              password must be provided to sign in. If false, a user may sign in via either
              email/password or email link.
      - !ruby/object:Api::Type::NestedObject
        name: phoneNumber
        description: |
          Configuration options related to authenticated a user by their phone number.
        properties:
          - !ruby/object:Api::Type::Boolean
            name: enabled
            description: |
              Whether phone number auth is enabled for the project or not.
          - !ruby/object:Api::Type::KeyValuePairs
            name: 'testPhoneNumbers'
            description: |
              A map of <test phone number, fake code> that can be used for phone auth testing.
      - !ruby/object:Api::Type::NestedObject
        name: anonymous
        description: |
          Configuration options related to authenticating an anonymous user.
        properties:
          - !ruby/object:Api::Type::Boolean
            name: enabled
            required: true
            description: |
              Whether anonymous user auth is enabled for the project or not.
      - !ruby/object:Api::Type::Boolean
        name: allowDuplicateEmails
        description: |
          Whether to allow more than one account to have the same email.
      - !ruby/object:Api::Type::NestedObject
        name: hashConfig
        output: true
        description: |
          Output only. Hash config information.
        properties:
          - !ruby/object:Api::Type::String
            name: algorithm
            output: true
            description: |
              Different password hash algorithms used in Identity Toolkit.
          - !ruby/object:Api::Type::String
            name: 'signerKey'
            output: true
            description: |
              Signer key in base64.
          - !ruby/object:Api::Type::String
            name: 'saltSeparator'
            output: true
            description: |
              Non-printable character to be inserted between the salt and plain text password in base64.
          - !ruby/object:Api::Type::Integer
            name: rounds
            output: true
            description: |
              How many rounds for hash calculation. Used by scrypt and other similar password derivation algorithms.
          - !ruby/object:Api::Type::Integer
            name: 'memoryCost'
            output: true
            description: |
              Memory cost for hash calculation. Used by scrypt and other similar password derivation algorithms. See https://tools.ietf.org/html/rfc7914 for explanation of field.
