# Copyright 2024 Google Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
name: 'VpcFlowLogsConfig'
description:
  VPC Flow Logs Config is a resource that lets you configure
  Flow Logs for VPC, Interconnect attachments or VPN Tunnels.
id_format: 'projects/{{project}}/locations/{{location}}/vpcFlowLogsConfigs/{{vpc_flow_logs_config_id}}'
base_url: 'projects/{{project}}/locations/{{location}}/vpcFlowLogsConfigs'
self_link: 'projects/{{project}}/locations/{{location}}/vpcFlowLogsConfigs/{{vpc_flow_logs_config_id}}'
create_url: 'projects/{{project}}/locations/{{location}}/vpcFlowLogsConfigs?vpcFlowLogsConfigId={{vpc_flow_logs_config_id}}'
update_verb: 'PATCH'
update_mask: true
import_format:
  - 'projects/{{project}}/locations/{{location}}/vpcFlowLogsConfigs/{{vpc_flow_logs_config_id}}'
timeouts:
  insert_minutes: 20
  update_minutes: 20
  delete_minutes: 20
autogen_async: true
async:
  actions: ['create', 'delete', 'update']
  type: 'OpAsync'
  operation:
    base_url: '{{op_id}}'
  result:
    resource_inside_response: true
custom_code:
sweeper:
  url_substitutions:
    - region: "global"
examples:
  - name: 'network_management_vpc_flow_logs_config_interconnect_full'
    primary_resource_id: 'interconnect-test'
    vars:
      network_name: 'full-interconnect-test-network'
      router_name: 'full-interconnect-test-router'
      vpc_flow_logs_config_id: 'full-interconnect-test-id'
      interconnect_attachment_name: 'full-interconnect-test-id'
  - name: 'network_management_vpc_flow_logs_config_interconnect_basic'
    primary_resource_id: 'interconnect-test'
    vars:
      network_name: 'basic-interconnect-test-network'
      router_name: 'basic-interconnect-test-router'
      vpc_flow_logs_config_id: 'basic-interconnect-test-id'
      interconnect_attachment_name: 'basic-interconnect-test-id'
  - name: 'network_management_vpc_flow_logs_config_vpn_basic'
    primary_resource_id: 'vpn-test'
    vars:
      network_name: 'basic-test-network'
      vpn_tunnel_name: 'basic-test-tunnel'
      target_vpn_gateway_name: 'basic-test-gateway'
      address_name: 'basic-test-address'
      udp500_forwarding_rule_name: 'basic-test-fr500'
      udp4500_forwarding_rule_name: 'basic-test-fr4500'
      esp_forwarding_rule_name: 'basic-test-fresp'
      route_name: 'basic-test-route'
      vpc_flow_logs_config_id: 'basic-test-id'
  - name: 'network_management_vpc_flow_logs_config_vpn_full'
    primary_resource_id: 'vpn-test'
    vars:
      network_name: 'full-test-network'
      vpn_tunnel_name: 'full-test-tunnel'
      target_vpn_gateway_name: 'full-test-gateway'
      address_name: 'full-test-address'
      udp500_forwarding_rule_name: 'full-test-fr500'
      udp4500_forwarding_rule_name: 'full-test-fr4500'
      esp_forwarding_rule_name: 'full-test-fresp'
      route_name: 'full-test-route'
      vpc_flow_logs_config_id: 'full-test-id'
  - name: 'network_management_vpc_flow_logs_config_network_basic'
    primary_resource_id: 'network-test'
    min_version: 'beta'
    vars:
      network_name: 'basic-network-test-network'
      vpc_flow_logs_config_id: 'basic-network-test-id'
  - name: 'network_management_vpc_flow_logs_config_network_full'
    primary_resource_id: 'network-test'
    min_version: 'beta'
    vars:
      network_name: 'full-network-test-network'
      vpc_flow_logs_config_id: 'full-network-test-id'
  - name: 'network_management_vpc_flow_logs_config_subnet_basic'
    primary_resource_id: 'subnet-test'
    min_version: 'beta'
    vars:
      network_name: 'basic-subnet-test-network'
      subnetwork_name: 'basic-subnet-test-subnetwork'
      vpc_flow_logs_config_id: 'basic-subnet-test-id'
  - name: 'network_management_vpc_flow_logs_config_subnet_full'
    primary_resource_id: 'subnet-test'
    min_version: 'beta'
    vars:
      network_name: 'full-subnet-test-network'
      subnetwork_name: 'full-subnet-test-subnetwork'
      vpc_flow_logs_config_id: 'full-subnet-test-id'
parameters:
  - name: 'location'
    type: String
    description: |
      Resource ID segment making up resource `name`. It identifies the resource
      within its parent collection as described in https://google.aip.dev/122. See documentation
      for resource type `networkmanagement.googleapis.com/VpcFlowLogsConfig`.
    url_param_only: true
    required: true
    immutable: true
  - name: 'vpcFlowLogsConfigId'
    type: String
    description: |
      Required. ID of the `VpcFlowLogsConfig`.
    url_param_only: true
    required: true
    immutable: true
properties:
  - name: 'name'
    type: String
    description: |
      Identifier. Unique name of the configuration using the form:     `projects/{project_id}/locations/global/vpcFlowLogsConfigs/{vpc_flow_logs_config_id}`
    output: true
  - name: 'description'
    type: String
    description: |
      Optional. The user-supplied description of the VPC Flow Logs configuration. Maximum
      of 512 characters.
  - name: 'state'
    type: String
    default_from_api: true
    description: |
      Optional. The state of the VPC Flow Log configuration. Default value
      is ENABLED. When creating a new configuration, it must be enabled.
      Possible values: STATE_UNSPECIFIED ENABLED DISABLED
  - name: 'aggregationInterval'
    type: String
    default_from_api: true
    description: |
      Optional. The aggregation interval for the logs. Default value is
      INTERVAL_5_SEC.   Possible values:  AGGREGATION_INTERVAL_UNSPECIFIED INTERVAL_5_SEC INTERVAL_30_SEC INTERVAL_1_MIN INTERVAL_5_MIN INTERVAL_10_MIN INTERVAL_15_MIN
  - name: 'flowSampling'
    type: Double
    default_from_api: true
    description: |
      Optional. The value of the field must be in (0, 1]. The sampling rate
      of VPC Flow Logs where 1.0 means all collected logs are reported. Setting the
      sampling rate to 0.0 is not allowed. If you want to disable VPC Flow Logs, use
      the state field instead. Default value is 1.0.
  - name: 'metadata'
    type: String
    default_from_api: true
    description: |
      Optional. Configures whether all, none or a subset of metadata fields
      should be added to the reported VPC flow logs. Default value is INCLUDE_ALL_METADATA.
        Possible values:  METADATA_UNSPECIFIED INCLUDE_ALL_METADATA EXCLUDE_ALL_METADATA CUSTOM_METADATA
  - name: 'metadataFields'
    type: Array
    description: |
      Optional. Custom metadata fields to include in the reported VPC flow
      logs. Can only be specified if \"metadata\" was set to CUSTOM_METADATA.
    item_type:
      type: String
  - name: 'filterExpr'
    type: String
    description: |
      Optional. Export filter used to define which VPC Flow Logs should be logged.
  - name: 'interconnectAttachment'
    type: String
    description: |
      Traffic will be logged from the Interconnect Attachment. Format: projects/{project_id}/regions/{region}/interconnectAttachments/{name}
  - name: 'vpnTunnel'
    type: String
    description: |
      Traffic will be logged from the VPN Tunnel. Format: projects/{project_id}/regions/{region}/vpnTunnels/{name}
  - name: 'subnet'
    min_version: 'beta'
    type: String
    description: |
      Traffic will be logged from VMs within the subnetwork. Format: projects/{project_id}/regions/{region}/subnetworks/{name}
  - name: 'network'
    min_version: 'beta'
    type: String
    description: |
      Traffic will be logged from VMs, VPN tunnels and Interconnect Attachments within the network. Format: projects/{project_id}/global/networks/{name}
  - name: 'labels'
    type: KeyValueLabels
    description: |
      Optional. Resource labels to represent user-provided metadata.
  - name: 'createTime'
    type: String
    description: |
      Output only. The time the config was created.
    output: true
  - name: 'updateTime'
    type: String
    description: |
      Output only. The time the config was updated.
    output: true
  - name: 'targetResourceState'
    type: String
    description: |-
      Describes the state of the configured target resource for diagnostic
      purposes.
      Possible values:
      TARGET_RESOURCE_STATE_UNSPECIFIED
      TARGET_RESOURCE_EXISTS
      TARGET_RESOURCE_DOES_NOT_EXIST
    output: true
  - name: crossProjectMetadata
    min_version: 'beta'
    type: String
    optional: true
    computed: true
    description: |-
      Determines whether to include cross project annotations in the logs.
      This field is available only for organization configurations. If not
      specified in org configs will be set to CROSS_PROJECT_METADATA_ENABLED.
      Possible values:
      CROSS_PROJECT_METADATA_UNSPECIFIED
      CROSS_PROJECT_METADATA_ENABLED
      CROSS_PROJECT_METADATA_DISABLED
