# Copyright 2024 Google Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
name: 'InterceptDeployment'
description: InterceptDeployment represents the collectors within a Zone and is associated with a deployment group.
min_version: 'beta'
docs:
id_format: 'projects/{{project}}/locations/{{location}}/interceptDeployments/{{intercept_deployment_id}}'
base_url: 'projects/{{project}}/locations/{{location}}/interceptDeployments'
self_link: 'projects/{{project}}/locations/{{location}}/interceptDeployments/{{intercept_deployment_id}}'
create_url: 'projects/{{project}}/locations/{{location}}/interceptDeployments?interceptDeploymentId={{intercept_deployment_id}}'
update_verb: 'PATCH'
update_mask: true
import_format:
  - 'projects/{{project}}/locations/{{location}}/interceptDeployments/{{intercept_deployment_id}}'
timeouts:
  insert_minutes: 20
  update_minutes: 20
  delete_minutes: 20
autogen_async: true
async:
  actions: ['create', 'delete', 'update']
  type: 'OpAsync'
  operation:
    base_url: '{{op_id}}'
  result:
    resource_inside_response: true
custom_code:
examples:
  - name: 'network_security_intercept_deployment_basic'
    config_path: 'templates/terraform/examples/network_security_intercept_deployment_basic.tf.tmpl'
    primary_resource_id: 'default'
    vars:
      network_name: 'example-network'
      subnetwork_name: 'example-subnet'
      health_check_name: 'example-hc'
      backend_service_name: 'example-bs'
      forwarding_rule_name: 'example-fwr'
      deployment_group_id: 'example-dg'
      deployment_id: 'example-deployment'
parameters:
  - name: 'location'
    type: String
    description: 'Resource ID segment making up resource `name`. It identifies the resource
    within its parent collection as described in https://google.aip.dev/122. See documentation
    for resource type `networksecurity.googleapis.com/InterceptDeployment`. '
    min_version: 'beta'
    url_param_only: true
    required: true
    immutable: true
  - name: 'interceptDeploymentId'
    type: String
    description: "Id of the requesting object\nIf auto-generating Id server-side,
    remove this field and\nintercept_deployment_id from the method_signature of Create
    RPC "
    min_version: 'beta'
    url_param_only: true
    required: true
    immutable: true
properties:
  - name: 'name'
    type: String
    description: 'Identifier. The name of the InterceptDeployment. '
    min_version: 'beta'
    output: true
  - name: 'createTime'
    type: String
    description: 'Create time stamp '
    min_version: 'beta'
    output: true
  - name: 'updateTime'
    type: String
    description: 'Update time stamp '
    min_version: 'beta'
    output: true
  - name: 'labels'
    type: KeyValueLabels
    description: 'Optional. Labels as key value pairs '
    min_version: 'beta'
  - name: 'forwardingRule'
    type: String
    description: "Immutable. The regional load balancer which the intercepted
    traffic should be forwarded\nto. Format is:\nprojects/{project}/regions/{region}/forwardingRules/{forwardingRule} "
    min_version: 'beta'
    required: true
    immutable: true
  - name: 'interceptDeploymentGroup'
    type: String
    description: "Immutable. The Intercept Deployment Group that this resource
    is part of. Format is:\n`projects/{project}/locations/global/interceptDeploymentGroups/{interceptDeploymentGroup}` "
    min_version: 'beta'
    required: true
    immutable: true
  - name: 'state'
    type: String
    description: "Current state of the deployment. \n Possible values:\n
    STATE_UNSPECIFIED\nACTIVE\nCREATING\nDELETING\nOUT_OF_SYNC\nDELETE_FAILED"
    min_version: 'beta'
    output: true
  - name: 'reconciling'
    type: Boolean
    description: "Whether reconciling is in progress, recommended per\nhttps://google.aip.dev/128. "
    min_version: 'beta'
    output: true
