# Copyright 2024 Google Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
name: 'WidgetConfig'
description: 'Represents a WidgetConfig.'
references:
  api: 'https://cloud.google.com/gemini/enterprise/docs/reference/rest/v1alpha/projects.locations.collections.engines.widgetConfigs'
base_url: 'projects/{{project}}/locations/{{location}}/collections/{{collection_id}}/engines/{{engine_id}}/widgetConfigs'
self_link: 'projects/{{project}}/locations/{{location}}/collections/{{collection_id}}/engines/{{engine_id}}/widgetConfigs/{{widget_config_id}}'
create_url: 'projects/{{project}}/locations/{{location}}/collections/{{collection_id}}/engines/{{engine_id}}/widgetConfigs/{{widget_config_id}}'
create_verb: 'PATCH'
update_verb: 'PATCH'
update_mask: true
exclude_delete: true
import_format:
  - 'projects/{{project}}/locations/{{location}}/collections/{{collection_id}}/engines/{{engine_id}}/widgetConfigs/{{widget_config_id}}'
timeouts:
  insert_minutes: 5
  update_minutes: 5
examples:
  - name: 'discoveryengine_widgetconfig_basic'
    primary_resource_id: 'basic'
    vars:
      data_store_id: 'data-store-id'
      engine_id: 'engine-id'
custom_code:
  pre_create: 'templates/terraform/pre_create/discoveryengine_widget_config.go.tmpl'
parameters:
  - name: 'location'
    type: String
    description: |
      The geographic location where the data store should reside. The value can
      only be one of "global", "us" and "eu".
    url_param_only: true
    required: true
    immutable: true
  - name: 'collectionId'
    type: String
    description: 'The collection ID.'
    url_param_only: true
    immutable: true
    default_value: 'default_collection'
  - name: 'engineId'
    type: String
    description: 'The engine ID.'
    required: true
    url_param_only: true
    immutable: true
  - name: 'widgetConfigId'
    type: String
    description: |
      The unique ID to use for the WidgetConfig. Currently only accepts "default_search_widget_config".
    url_param_only: true
    immutable: true
    default_value: 'default_search_widget_config'
properties:
  - name: 'name'
    type: String
    description: |
      The full resource name of the widget config. Format:
      `projects/{project}/locations/{location}/collections/{collection_id}/engines/{engine_id}/widgetConfigs/{widget_config_id}`.
    output: true
  - name: 'accessSettings'
    type: NestedObject
    description: 'Describes widget access settings.'
    default_from_api: true
    properties:
      - name: 'allowPublicAccess'
        type: Boolean
        description: 'Whether public unauthenticated access is allowed.'
      - name: 'allowlistedDomains'
        type: Array
        description: 'List of domains that are allowed to integrate the search widget.'
        item_type:
          type: String
      - name: 'enableWebApp'
        type: Boolean
        description: 'Whether web app access is enabled.'
      - name: 'workforceIdentityPoolProvider'
        type: String
        description: |
          The workforce identity pool provider used to access the widget.
      - name: 'languageCode'
        type: String
        description: |
          Language code for user interface. Use language tags defined by
          [BCP47](https://www.rfc-editor.org/rfc/bcp/bcp47.txt). If unset, the
          default language code is "en-US".

  - name: 'uiSettings'
    type: NestedObject
    description: 'Describes general widget (or web app) UI settings as seen in the cloud console UI configuration page.'
    default_from_api: true
    properties:
      - name: 'interactionType'
        type: Enum
        description: 'Describes widget (or web app) interaction type'
        enum_values:
          - 'SEARCH_ONLY'
          - 'SEARCH_WITH_ANSWER'
          - 'SEARCH_WITH_FOLLOW_UPS'
      - name: 'generativeAnswerConfig'
        type: NestedObject
        description: 'Describes generative answer configuration.'
        properties:
          - name: 'resultCount'
            type: Integer
            description: |
              The number of top results to generate the answer from. Up to 10.
          - name: 'modelVersion'
            type: String
            description: |
              The model version used to generate the answer.
          - name: 'modelPromptPreamble'
            type: String
            description: |
              Text at the beginning of the prompt that instructs the model that generates the answer.
          - name: 'maxRephraseSteps'
            type: Integer
            description: |
              Max rephrase steps. The max number is 5 steps. If not set or
              set to < 1, it will be set to 1 by default.
          - name: 'languageCode'
            type: String
            description: |
              Language code for Summary. Use language tags defined by
              [BCP47](https://www.rfc-editor.org/rfc/bcp/bcp47.txt). Note: This
              is an experimental feature.
          - name: 'disableRelatedQuestions'
            type: Boolean
            description: |
              Whether generated answer contains suggested related questions.
          - name: 'ignoreNonAnswerSeekingQuery'
            type: Boolean
            description: |
              Specifies whether to filter out queries that are not answer-seeking.
              The default value is `false`. No answer is returned if the search query
              is classified as a non-answer seeking query.
              If this field is set to `true`, we skip generating answers for
              non-answer seeking queries and return fallback messages instead.
          - name: 'ignoreAdversarialQuery'
            type: Boolean
            description: |
              Specifies whether to filter out queries that are adversarial.
          - name: 'ignoreLowRelevantContent'
            type: Boolean
            description: |
              Specifies whether to filter out queries that are not relevant to the content.
          - name: 'imageSource'
            type: Enum
            description: 'Source of image returned in the answer.'
            enum_values:
              - 'ALL_AVAILABLE_SOURCES'
              - 'CORPUS_IMAGE_ONLY'
              - 'FIGURE_GENERATION_ONLY'
      - name: 'resultDescriptionType'
        type: Enum
        description: |
          Controls whether result extract is display and how (snippet or extractive answer).
          Default to no result if unspecified.
        enum_values:
          - 'SNIPPET'
          - 'EXTRACTIVE_ANSWER'
      - name: 'enableAutocomplete'
        type: Boolean
        description: 'Whether or not to enable autocomplete.'
      - name: 'enableSafeSearch'
        type: Boolean
        description: 'Whether to enable safe search.'
      - name: 'enableQualityFeedback'
        type: Boolean
        description: |
          Turn on or off collecting the search result quality feedback from end users.
      - name: 'enableSearchAsYouType'
        type: Boolean
        description: |
          Whether to enable search-as-you-type behavior for the search widget.
      - name: 'defaultSearchRequestOrderBy'
        type: String
        description: |
          The default ordering for search results if specified.
          Used to set SearchRequest#orderBy on applicable requests.
      - name: 'dataStoreUiConfigs'
        type: Array
        description: 'Per data store configuration.'
        item_type:
          type: NestedObject
          properties:
            - name: 'name'
              type: String
              description: |
                The name of the data store. It should be data store resource name. Format:
                `projects/{project}/locations/{location}/collections/{collectionId}/dataStores/{dataStoreId}`.
                For APIs under `WidgetService`, such as [WidgetService.LookUpWidgetConfig][],
                the project number and location part is erased in this field.
            - name: 'facetField'
              type: Array
              item_type:
                type: NestedObject
                properties:
                  - name: 'field'
                    type: String
                    description: 'Registered field name. The format is `field.abc`.'
                    required: true
                  - name: 'displayName'
                    type: String
                    description: 'The field name that end users will see.'
            - name: 'fieldsUiComponentsMap'
              type: Map
              description: |
                'The key is the UI component. Currently supported `title`, `thumbnail`,
                `url`, `custom1`, `custom2`, `custom3`. The value is the name of
                the field along with its device visibility. The 3 custom fields are optional
                and can be added or removed.
                `title`, `thumbnail`, `url` are required UI components that cannot be removed.
              key_name: 'ui_component'
              value_type:
                type: NestedObject
                description: |
                  The name of the field along with its device visibility and display template.
                properties:
                  - name: 'field'
                    type: String
                    description: 'Registered field name. The format is `field.abc`.'
                    required: true
                  - name: 'deviceVisibility'
                    type: Array
                    item_type:
                      type: Enum
                      enum_values:
                        - 'MOBILE'
                        - 'DESKTOP'
                  - name: 'displayTemplate'
                    type: String
                    description: |
                      The template to customize how the field is displayed.
                      An example value would be a string that looks like: "Price: {value}".
      - name: 'disableUserEventsCollection'
        type: Boolean
        description: 'If set to true, the widget will not collect user events.'
      - name: 'enableVisualContentSummary'
        type: Boolean
        description: |
          If set to true, the widget will enable visual content summary on applicable
          search requests. Only used by healthcare search.
      - name: 'enablePeopleSearch'
        type: Boolean
        description: 'If set to true, the widget will enable people search.'
      - name: 'enableCreateAgentButton'
        type: Boolean
        description: 'If set to true, the widget will enable the create agent button.'
  - name: 'uiBranding'
    type: NestedObject
    description: |
      Describes search widget UI branding settings, such as the widget title, logo,
      favicons, and colors.
    properties:
      - name: 'logo'
        type: NestedObject
        description: 'Logo image.'
        properties:
          - name: 'url'
            type: String
            description: 'Image URL.'
            exactly_one_of:
              - 'url'
  - name: 'homepageSetting'
    type: NestedObject
    description: |
      Describes the homepage setting of the widget. It includes all homepage related settings
      and configurations, such as shortcuts.
    properties:
      - name: 'shortcuts'
        type: Array
        description: 'The shortcuts to display on the homepage.'
        item_type:
          type: NestedObject
          properties:
            - name: 'title'
              type: String
              description: 'Title of the shortcut.'
            - name: 'icon'
              type: NestedObject
              description: 'Icon URL of shortcut.'
              properties:
                - name: 'url'
                  type: String
                  description: 'Image URL.'
                  exactly_one_of:
                    - 'url'
            - name: 'destinationUri'
              type: String
              description: 'Destination URL of shortcut.'
