# Copyright 2023 Google Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

--- !ruby/object:Api::Resource
name: 'Service'
base_url: services
self_link: services/{{service_name}}
description: |
  A service that is managed by Google Service Management
legacy_name: google_endpoints_service
id_format: 'services/{{service_name}}'
import_format: ['services/{{service_name}}']
exclude_resource: true
iam_policy: !ruby/object:Api::Resource::IamPolicy
  parent_resource_attribute: 'service_name'
  method_name_separator: ':'
  fetch_iam_policy_verb: :POST
examples:
  - !ruby/object:Provider::Terraform::Examples
    name: 'endpoints_iam'
    primary_resource_id: 'endpoints_service'
    primary_resource_name: "fmt.Sprintf(\"endpoint%s.endpoints.%s.cloud.goog\",
      context[\"\
      random_suffix\"], context[\"project_name\"])"
    vars:
      name: 'endpoint'
    test_env_vars:
      project_name: :PROJECT_NAME
properties:
  - !ruby/object:Api::Type::String
    name: 'serviceName'
    description: The name of the service.
    required: true
