# Copyright 2023 Google Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

--- !ruby/object:Api::Resource
name: RepositoryWorkflowConfig
base_url: projects/{{project}}/locations/{{region}}/repositories/{{repository}}/workflowConfigs
create_url: projects/{{project}}/locations/{{region}}/repositories/{{repository}}/workflowConfigs?workflowConfigId={{name}}
create_verb: :POST
update_verb: :PATCH
min_version: beta
description: |-
  A resource represents a Dataform workflow configuration
references: !ruby/object:Api::Resource::ReferenceLinks
  guides:
    'Official Documentation': 'https://cloud.google.com/dataform/docs/workflow-configurations'
  api: 'https://cloud.google.com/dataform/reference/rest/v1beta1/projects.locations.repositories.workflowConfigs'
id_format: projects/{{project}}/locations/{{region}}/repositories/{{repository}}/workflowConfigs/{{name}}
import_format:
  ['projects/{{project}}/locations/{{region}}/repositories/{{repository}}/workflowConfigs/{{name}}']
examples:
  - !ruby/object:Provider::Terraform::Examples
    name: 'dataform_repository_workflow_config'
    primary_resource_id: workflow
    min_version: beta
    vars:
      workflow_name: 'my_workflow'
      release_name: 'my_release'
      service_account_name: 'dataform-sa'
      git_repository_name: 'my/repository'
      dataform_repository_name: 'dataform_repository'
      data: secret-data
      secret_name: my_secret
parameters:
  - !ruby/object:Api::Type::String
    name: 'region'
    description: 'A reference to the region'
    immutable: true
    url_param_only: true
  - !ruby/object:Api::Type::String
    name: 'repository'
    description: 'A reference to the Dataform repository'
    immutable: true
    url_param_only: true
properties:
  - !ruby/object:Api::Type::String
    name: 'name'
    description: The workflow's name.
    immutable: true
    required: true
    custom_flatten: 'templates/terraform/custom_flatten/name_from_self_link.erb'
  - !ruby/object:Api::Type::String
    name: 'releaseConfig'
    required: true
    description:
      The name of the release config whose releaseCompilationResult should be executed.
      Must be in the format projects/*/locations/*/repositories/*/releaseConfigs/*.
  - !ruby/object:Api::Type::NestedObject
    name: 'invocationConfig'
    description:
      Optional. If left unset, a default InvocationConfig will be used.
    properties:
      - !ruby/object:Api::Type::Array
        name: 'includedTargets'
        description: Optional. The set of action identifiers to include.
        item_type: !ruby/object:Api::Type::NestedObject
          properties:
            - !ruby/object:Api::Type::String
              name: 'database'
              description: The action's database (Google Cloud project ID).
            - !ruby/object:Api::Type::String
              name: 'schema'
              description:
                The action's schema (BigQuery dataset ID), within database.
            - !ruby/object:Api::Type::String
              name: 'name'
              description:
                The action's name, within database and schema.
      - !ruby/object:Api::Type::Array
        name: 'includedTags'
        description: Optional. The set of tags to include.
        item_type: Api::Type::String
      - !ruby/object:Api::Type::Boolean
        name: 'transitiveDependenciesIncluded'
        description: Optional. When set to true, transitive dependencies of included actions will be executed.
      - !ruby/object:Api::Type::Boolean
        name: 'transitiveDependentsIncluded'
        description: Optional. When set to true, transitive dependents of included actions will be executed.
      - !ruby/object:Api::Type::Boolean
        name: 'fullyRefreshIncrementalTablesEnabled'
        description: Optional. When set to true, any incremental tables will be fully refreshed.
      - !ruby/object:Api::Type::String
        name: 'serviceAccount'
        description: Optional. The service account to run workflow invocations under.
  - !ruby/object:Api::Type::String
    name: 'cronSchedule'
    description:
      Optional. Optional schedule (in cron format) for automatic creation of compilation results.
  - !ruby/object:Api::Type::String
    name: 'timeZone'
    description:
      Optional. Specifies the time zone to be used when interpreting cronSchedule.
      Must be a time zone name from the time zone database (https://en.wikipedia.org/wiki/List_of_tz_database_time_zones).
      If left unspecified, the default is UTC.
  - !ruby/object:Api::Type::Array
    name: 'recentScheduledExecutionRecords'
    description:
      Records of the 10 most recent scheduled execution attempts,
      ordered in in descending order of executionTime.
      Updated whenever automatic creation of a workflow invocation is triggered by cronSchedule.
    output: true
    item_type: !ruby/object:Api::Type::NestedObject
      properties:
        - !ruby/object:Api::Type::String
          name: 'executionTime'
          output: true
          description: The timestamp of this workflow attempt.
        - !ruby/object:Api::Type::String
          name: 'workflowInvocation'
          output: true
          description:
            The name of the created workflow invocation, if one was successfully created.
            In the format projects/*/locations/*/repositories/*/workflowInvocations/*.
        - !ruby/object:Api::Type::NestedObject
          name: 'errorStatus'
          output: true
          description:
            The error status encountered upon this attempt to create the workflow invocation,
            if the attempt was unsuccessful.
          properties:
            - !ruby/object:Api::Type::Integer
              name: 'code'
              output: true
              description: The status code, which should be an enum value of google.rpc.Code.
            - !ruby/object:Api::Type::String
              name: 'message'
              output: true
              description:
                A developer-facing error message, which should be in English.
                Any user-facing error message should be localized and sent in
                the google.rpc.Status.details field, or localized by the client.
