# Copyright 2023 Google Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

--- !ruby/object:Api::Resource
name: 'Service'
base_url: 'projects/{{project}}/locations/{{location}}/services'
create_url: 'projects/{{project}}/locations/{{location}}/services?serviceId={{service_id}}'
self_link: 'projects/{{project}}/locations/{{location}}/services/{{service_id}}'
update_verb: :PATCH
update_mask: true
description: |
  A managed metastore service that serves metadata queries.
references: !ruby/object:Api::Resource::ReferenceLinks
  guides:
    'Official Documentation': 'https://cloud.google.com/dataproc-metastore/docs/overview'
  api: 'https://cloud.google.com/dataproc-metastore/docs/reference/rest/v1/projects.locations.services'
iam_policy: !ruby/object:Api::Resource::IamPolicy
  parent_resource_attribute: service_id
  method_name_separator: ':'
  import_format:
    [
      'projects/{{project}}/locations/{{location}}/services/{{service_id}}',
      '{{service_id}}',
    ]
async: !ruby/object:Api::OpAsync
  operation: !ruby/object:Api::OpAsync::Operation
    path: 'name'
    base_url: '{{op_id}}'
    wait_ms: 1000
    timeouts: !ruby/object:Api::Timeouts
      insert_minutes: 60
      update_minutes: 60
      delete_minutes: 60
  result: !ruby/object:Api::OpAsync::Result
    path: 'response'
  status: !ruby/object:Api::OpAsync::Status
    path: 'done'
    complete: true
    allowed:
      - true
      - false
  error: !ruby/object:Api::OpAsync::Error
    path: 'error'
    message: 'message'
autogen_async: true
import_format:
  ['projects/{{project}}/locations/{{location}}/services/{{service_id}}']
examples:
  - !ruby/object:Provider::Terraform::Examples
    name: 'dataproc_metastore_service_basic'
    primary_resource_name:
      'fmt.Sprintf("tf-test-metastore-srv%s", context["random_suffix"])'
    primary_resource_id: 'default'
    vars:
      metastore_service_name: 'metastore-srv'
  - !ruby/object:Provider::Terraform::Examples
    name: 'dataproc_metastore_service_cmek_test'
    skip_docs: true
    primary_resource_id: 'default'
    vars:
      metastore_service_name: 'example-service'
      key_name: 'example-key'
      keyring_name: 'example-keyring'
  - !ruby/object:Provider::Terraform::Examples
    name: 'dataproc_metastore_service_cmek_example'
    skip_test: true
    primary_resource_id: 'default'
    vars:
      metastore_service_name: 'example-service'
      key_name: 'example-key'
      keyring_name: 'example-keyring'
  - !ruby/object:Provider::Terraform::Examples
    name: 'dataproc_metastore_service_endpoint'
    min_version: beta
    skip_docs: true
    skip_test: true  # https://github.com/hashicorp/terraform-provider-google/issues/13710
    primary_resource_id: 'endpoint'
    vars:
      metastore_service_name: 'metastore-endpoint'
  - !ruby/object:Provider::Terraform::Examples
    name: 'dataproc_metastore_service_aux'
    min_version: beta
    skip_docs: true
    primary_resource_id: 'aux'
    vars:
      metastore_service_name: 'metastore-aux'
  - !ruby/object:Provider::Terraform::Examples
    name: 'dataproc_metastore_service_metadata'
    min_version: beta
    skip_docs: true
    primary_resource_id: 'metadata'
    vars:
      metastore_service_name: 'metastore-metadata'
  - !ruby/object:Provider::Terraform::Examples
    name: 'dataproc_metastore_service_private_service_connect'
    skip_test: true
    primary_resource_id: default
    vars:
      metastore_service_name: 'metastore-srv'
      network_name: 'my-network'
      subnet_name: 'my-subnetwork'
  - !ruby/object:Provider::Terraform::Examples
    name: 'dataproc_metastore_service_telemetry'
    skip_docs: true
    primary_resource_id: 'telemetry'
    vars:
      metastore_service_name: 'telemetry'
parameters:
  - !ruby/object:Api::Type::String
    name: 'serviceId'
    required: true
    immutable: true
    url_param_only: true
    description: |
      The ID of the metastore service. The id must contain only letters (a-z, A-Z), numbers (0-9), underscores (_),
      and hyphens (-). Cannot begin or end with underscore or hyphen. Must consist of between
      3 and 63 characters.
  - !ruby/object:Api::Type::String
    name: 'location'
    url_param_only: true
    immutable: true
    default_value: global
    description: |
      The location where the metastore service should reside.
      The default value is `global`.
properties:
  - !ruby/object:Api::Type::String
    name: 'name'
    output: true
    description: |
      The relative resource name of the metastore service.
  - !ruby/object:Api::Type::KeyValuePairs
    name: 'labels'
    description: 'User-defined labels for the metastore service.'
  # This is an x-product resource reference.
  - !ruby/object:Api::Type::String
    name: 'network'
    immutable: true
    description: |
      The relative resource name of the VPC network on which the instance can be accessed. It is specified in the following form:

      "projects/{projectNumber}/global/networks/{network_id}".
    default_from_api: true
  - !ruby/object:Api::Type::String
    name: 'endpointUri'
    output: true
    description: |
      The URI of the endpoint used to access the metastore service.
  - !ruby/object:Api::Type::Integer
    name: 'port'
    description: |
      The TCP port at which the metastore service is reached. Default: 9083.
    default_from_api: true
  - !ruby/object:Api::Type::String
    name: 'state'
    output: true
    description: |
      The current state of the metastore service.
  - !ruby/object:Api::Type::String
    name: 'stateMessage'
    output: true
    description: |
      Additional information about the current state of the metastore service, if available.
  - !ruby/object:Api::Type::String
    name: 'artifactGcsUri'
    output: true
    description: |
      A Cloud Storage URI (starting with gs://) that specifies where artifacts related to the metastore service are stored.
  - !ruby/object:Api::Type::Enum
    name: 'tier'
    description: |
      The tier of the service.
    values:
      - :DEVELOPER
      - :ENTERPRISE
    default_from_api: true
  - !ruby/object:Api::Type::NestedObject
    name: 'maintenanceWindow'
    description: |
      The one hour maintenance window of the metastore service.
      This specifies when the service can be restarted for maintenance purposes in UTC time.
      Maintenance window is not needed for services with the `SPANNER` database type.
    properties:
      - !ruby/object:Api::Type::Integer
        name: 'hourOfDay'
        description: |
          The hour of day (0-23) when the window starts.
        required: true
      - !ruby/object:Api::Type::Enum
        name: 'dayOfWeek'
        description: |
          The day of week, when the window starts.
        required: true
        values:
          - :MONDAY
          - :TUESDAY
          - :WEDNESDAY
          - :THURSDAY
          - :FRIDAY
          - :SATURDAY
          - :SUNDAY
  - !ruby/object:Api::Type::NestedObject
    name: 'encryptionConfig'
    description: |
      Information used to configure the Dataproc Metastore service to encrypt
      customer data at rest.
    properties:
      - !ruby/object:Api::Type::String
        name: 'kmsKey'
        description: |
          The fully qualified customer provided Cloud KMS key name to use for customer data encryption.
          Use the following format: `projects/([^/]+)/locations/([^/]+)/keyRings/([^/]+)/cryptoKeys/([^/]+)`
        required: true
        immutable: true
  - !ruby/object:Api::Type::NestedObject
    name: 'hiveMetastoreConfig'
    description: |
      Configuration information specific to running Hive metastore software as the metastore service.
    properties:
      - !ruby/object:Api::Type::Enum
        name: 'endpointProtocol'
        min_version: beta
        immutable: true
        default_value: :THRIFT
        description: |
          The protocol to use for the metastore service endpoint. If unspecified, defaults to `THRIFT`.
        values:
          - :THRIFT
          - :GRPC
      - !ruby/object:Api::Type::String
        name: 'version'
        immutable: true
        required: true
        description: |
          The Hive metastore schema version.
      - !ruby/object:Api::Type::KeyValuePairs
        name: 'configOverrides'
        description: |
          A mapping of Hive metastore configuration key-value pairs to apply to the Hive metastore (configured in hive-site.xml).
          The mappings override system defaults (some keys cannot be overridden)
        default_from_api: true
        diff_suppress_func: 'dataprocMetastoreServiceOverrideSuppress'
      - !ruby/object:Api::Type::NestedObject
        name: 'kerberosConfig'
        description: |
          Information used to configure the Hive metastore service as a service principal in a Kerberos realm.
        properties:
          - !ruby/object:Api::Type::NestedObject
            name: 'keytab'
            required: true
            description: |
              A Kerberos keytab file that can be used to authenticate a service principal with a Kerberos Key Distribution Center (KDC).
            properties:
              - !ruby/object:Api::Type::String
                required: true
                name: 'cloudSecret'
                description: |
                  The relative resource name of a Secret Manager secret version, in the following form:

                  "projects/{projectNumber}/secrets/{secret_id}/versions/{version_id}".
          - !ruby/object:Api::Type::String
            name: 'principal'
            required: true
            description: |
              A Kerberos principal that exists in the both the keytab the KDC to authenticate as. A typical principal is of the form "primary/instance@REALM", but there is no exact format.
          - !ruby/object:Api::Type::String
            name: 'krb5ConfigGcsUri'
            required: true
            description: |
              A Cloud Storage URI that specifies the path to a krb5.conf file. It is of the form gs://{bucket_name}/path/to/krb5.conf, although the file does not need to be named krb5.conf explicitly.
      - !ruby/object:Api::Type::Map
        name: 'auxiliaryVersions'
        min_version: beta
        description: |
          A mapping of Hive metastore version to the auxiliary version configuration.
          When specified, a secondary Hive metastore service is created along with the primary service.
          All auxiliary versions must be less than the service's primary version.
          The key is the auxiliary service name and it must match the regular expression a-z?.
          This means that the first character must be a lowercase letter, and all the following characters must be hyphens, lowercase letters, or digits, except the last character, which cannot be a hyphen.
        key_name: 'key'
        key_description: |
          The auxiliary service name
        value_type: !ruby/object:Api::Type::NestedObject
          properties:
            - !ruby/object:Api::Type::String
              name: 'version'
              required: true
              description: |
                The Hive metastore version of the auxiliary service. It must be less than the primary Hive metastore service's version.
            - !ruby/object:Api::Type::KeyValuePairs
              name: 'configOverrides'
              description: |
                A mapping of Hive metastore configuration key-value pairs to apply to the auxiliary Hive metastore (configured in hive-site.xml) in addition to the primary version's overrides.
                If keys are present in both the auxiliary version's overrides and the primary version's overrides, the value from the auxiliary version's overrides takes precedence.
  - !ruby/object:Api::Type::NestedObject
    name: 'networkConfig'
    immutable: true
    description: |
      The configuration specifying the network settings for the Dataproc Metastore service.
    properties:
      - !ruby/object:Api::Type::Array
        name: 'consumers'
        description: |
          The consumer-side network configuration for the Dataproc Metastore instance.
        required: true
        immutable: true
        item_type: !ruby/object:Api::Type::NestedObject
          properties:
            - !ruby/object:Api::Type::String
              name: 'endpointUri'
              description: |
                The URI of the endpoint used to access the metastore service.
              output: true
            - !ruby/object:Api::Type::String
              name: 'subnetwork'
              required: true
              description: |
                The subnetwork of the customer project from which an IP address is reserved and used as the Dataproc Metastore service's endpoint.
                It is accessible to hosts in the subnet and to all hosts in a subnet in the same region and same network.
                There must be at least one IP address available in the subnet's primary range. The subnet is specified in the following form:
                `projects/{projectNumber}/regions/{region_id}/subnetworks/{subnetwork_id}
  - !ruby/object:Api::Type::Enum
    name: 'databaseType'
    immutable: true
    default_value: :MYSQL
    description: |
      The database type that the Metastore service stores its data.
    values:
      - :MYSQL
      - :SPANNER
  - !ruby/object:Api::Type::Enum
    name: 'releaseChannel'
    immutable: true
    default_value: :STABLE
    description: |
      The release channel of the service. If unspecified, defaults to `STABLE`.
    values:
      - :CANARY
      - :STABLE
  - !ruby/object:Api::Type::String
    name: 'uid'
    output: true
    description: |
      The globally unique resource identifier of the metastore service.
  - !ruby/object:Api::Type::NestedObject
    name: 'metadataIntegration'
    min_version: beta
    description: |
      The setting that defines how metastore metadata should be integrated with external services and systems.
    properties:
      - !ruby/object:Api::Type::NestedObject
        name: 'dataCatalogConfig'
        required: true
        description: |
          The integration config for the Data Catalog service.
        properties:
          - !ruby/object:Api::Type::Boolean
            name: 'enabled'
            required: true
            description: |
              Defines whether the metastore metadata should be synced to Data Catalog. The default value is to disable syncing metastore metadata to Data Catalog.
  - !ruby/object:Api::Type::NestedObject
    name: 'telemetryConfig'
    description: |
      The configuration specifying telemetry settings for the Dataproc Metastore service. If unspecified defaults to JSON.
    default_from_api: true
    properties:
      - !ruby/object:Api::Type::Enum
        name: 'logFormat'
        default_value: :JSON
        description: |
          The output format of the Dataproc Metastore service's logs.
        values:
          - :LEGACY
          - :JSON
