# Copyright 2024 Google Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
name: 'ScanConfig'
description: |
  A ScanConfig resource contains the configurations to launch a scan.
min_version: 'beta'
references:
  guides:
    'Using Cloud Security Scanner': 'https://cloud.google.com/security-scanner/docs/scanning'
  api: 'https://cloud.google.com/security-scanner/docs/reference/rest/v1beta/projects.scanConfigs'
docs:
base_url: 'projects/{{project}}/scanConfigs'
self_link: '{{name}}'
update_verb: 'PATCH'
update_mask: true
timeouts:
  insert_minutes: 20
  update_minutes: 20
  delete_minutes: 20
custom_code:
  post_create: 'templates/terraform/post_create/set_computed_name.tmpl'
  custom_import: 'templates/terraform/custom_import/self_link_as_name.tmpl'
examples:
  - name: 'scan_config_basic'
    primary_resource_id: 'scan-config'
    min_version: 'beta'
    vars:
      address_name: 'scan-basic-static-ip'
      scan_config_name: 'terraform-scan-config'
parameters:
properties:
  - name: 'name'
    type: String
    description: |
      A server defined name for this index. Format:
      `projects/{{project}}/scanConfigs/{{server_generated_id}}`
    min_version: 'beta'
    output: true
  - name: 'displayName'
    type: String
    description: |
      The user provider display name of the ScanConfig.
    min_version: 'beta'
    required: true
  - name: 'maxQps'
    type: Integer
    description: |
      The maximum QPS during scanning. A valid value ranges from 5 to 20 inclusively.
      Defaults to 15.
    min_version: 'beta'
    validation:
      function: 'validation.IntBetween(5, 20)'
    default_value: 15
  - name: 'startingUrls'
    type: Array
    description: |
      The starting URLs from which the scanner finds site pages.
    min_version: 'beta'
    required: true
    item_type:
      type: String
  - name: 'authentication'
    type: NestedObject
    description: |
      The authentication configuration.
      If specified, service will use the authentication configuration during scanning.
    min_version: 'beta'
    properties:
      - name: 'googleAccount'
        type: NestedObject
        description: |
          Describes authentication configuration that uses a Google account.
        min_version: 'beta'
        at_least_one_of:
          - 'authentication.0.google_account'
          - 'authentication.0.custom_account'
        properties:
          - name: 'username'
            type: String
            description: |
              The user name of the Google account.
            min_version: 'beta'
            required: true
          - name: 'password'
            type: String
            description: |
              The password of the Google account. The credential is stored encrypted
              in GCP.
            min_version: 'beta'
            required: true
            immutable: true
            sensitive: true
            custom_flatten: 'templates/terraform/custom_flatten/scan_config_auth_custom_password.go.tmpl'
      - name: 'customAccount'
        type: NestedObject
        description: |
          Describes authentication configuration that uses a custom account.
        min_version: 'beta'
        at_least_one_of:
          - 'authentication.0.google_account'
          - 'authentication.0.custom_account'
        properties:
          - name: 'username'
            type: String
            description: |
              The user name of the custom account.
            min_version: 'beta'
            required: true
          - name: 'password'
            type: String
            description: |
              The password of the custom account. The credential is stored encrypted
              in GCP.
            min_version: 'beta'
            required: true
            immutable: true
            sensitive: true
            custom_flatten: 'templates/terraform/custom_flatten/scan_config_auth_google_password.go.tmpl'
          - name: 'loginUrl'
            type: String
            description: |
              The login form URL of the website.
            min_version: 'beta'
            required: true
  - name: 'userAgent'
    type: Enum
    description: Type of the user agents used for scanning
    min_version: 'beta'
    default_value: "CHROME_LINUX"
    enum_values:
      - 'USER_AGENT_UNSPECIFIED'
      - 'CHROME_LINUX'
      - 'CHROME_ANDROID'
      - 'SAFARI_IPHONE'
  - name: 'blacklistPatterns'
    type: Array
    description: |
      The blacklist URL patterns as described in
      https://cloud.google.com/security-scanner/docs/excluded-urls
    min_version: 'beta'
    item_type:
      type: String
  - name: 'schedule'
    type: NestedObject
    description: |
      The schedule of the ScanConfig
    min_version: 'beta'
    properties:
      - name: 'scheduleTime'
        type: Time
        description: |
          A timestamp indicates when the next run will be scheduled. The value is refreshed
          by the server after each run. If unspecified, it will default to current server time,
          which means the scan will be scheduled to start immediately.
        min_version: 'beta'
      - name: 'intervalDurationDays'
        type: Integer
        description: |
          The duration of time between executions in days
        min_version: 'beta'
        required: true
  - name: 'targetPlatforms'
    type: Array
    description: |
      Set of Cloud Platforms targeted by the scan. If empty, APP_ENGINE will be used as a default.
    min_version: 'beta'
    item_type:
      type: Enum
      description: |
        This field only has a name and description because of MM
        limitations. It should not appear in downstreams.
      enum_values:
        - 'APP_ENGINE'
        - 'COMPUTE'
  - name: 'exportToSecurityCommandCenter'
    type: Enum
    description: |
      Controls export of scan configurations and results to Cloud Security Command Center.
    min_version: 'beta'
    default_value: "ENABLED"
    enum_values:
      - 'ENABLED'
      - 'DISABLED'
