# Copyright 2024 Google Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

--- !ruby/object:Api::Resource
base_url: projects/{{project}}/locations/{{location}}/applications/{{application_id}}/services
create_url: projects/{{project}}/locations/{{location}}/applications/{{application_id}}/services?serviceId={{service_id}}
self_link: projects/{{project}}/locations/{{location}}/applications/{{application_id}}/services/{{service_id}}
id_format: projects/{{project}}/locations/{{location}}/applications/{{application_id}}/services/{{service_id}}
import_format:
  - projects/{{project}}/locations/{{location}}/applications/{{application_id}}/services/{{service_id}}
name: Service
description: 'Service is a network/api interface that exposes some functionality to clients for consumption over the network.
  Service typically has one or more Workloads behind it. It registers identified service to the Application.'
update_verb: :PATCH
update_mask: true
autogen_async: true
async: !ruby/object:Api::OpAsync
  operation: !ruby/object:Api::OpAsync::Operation
    path: name
    base_url: "{{op_id}}"
    wait_ms: 1000
    timeouts:
  result: !ruby/object:Api::OpAsync::Result
    path: response
    resource_inside_response: true
  status: !ruby/object:Api::OpAsync::Status
    path: done
    complete: true
    allowed:
      - true
      - false
  error: !ruby/object:Api::OpAsync::Error
    path: error
    message: message
examples:
  - !ruby/object:Provider::Terraform::Examples
    name: "apphub_service_basic"
    external_providers: ["random", "time"]
    primary_resource_id: "example"
    vars:
      application_id: "example-application-1"
      service_project_attachment_id: "project-1"
      ilb_network: "l7-ilb-network"
      ilb_subnet: "l7-ilb-subnet"
      forwarding_rule: "l7-ilb-forwarding-rule"
      backend_service: "l7-ilb-backend-subnet"
      health_check: "l7-ilb-hc"
    test_env_vars:
      org_id: :ORG_ID
      billing_account: :BILLING_ACCT
  - !ruby/object:Provider::Terraform::Examples
    name: "apphub_service_full"
    external_providers: ["random", "time"]
    primary_resource_id: "example"
    vars:
      application_id: "example-application-1"
      service_project_attachment_id: "project-1"
      display_name: "Example Service Full"
      description: 'Register service for testing'
      business_name: "Alice"
      business_email: "alice@google.com"
      developer_name: "Bob"
      developer_email: "bob@google.com"
      operator_name: "Charlie"
      operator_email: "charlie@google.com"
      ilb_network: "l7-ilb-network"
      ilb_subnet: "l7-ilb-subnet"
      forwarding_rule: "l7-ilb-forwarding-rule"
      backend_service: "l7-ilb-backend-subnet"
      health_check: "l7-ilb-hc"
    test_env_vars:
      org_id: :ORG_ID
      billing_account: :BILLING_ACCT
parameters:
  - !ruby/object:Api::Type::String
    name: location
    description: 'Part of `parent`.  Full resource name of a parent Application. Example: projects/{HOST_PROJECT_ID}/locations/{LOCATION}/applications/{APPLICATION_ID}'
    url_param_only: true
    required: true
    immutable: true
  - !ruby/object:Api::Type::String
    name: applicationId
    description: 'Part of `parent`.  Full resource name of a parent Application. Example: projects/{HOST_PROJECT_ID}/locations/{LOCATION}/applications/{APPLICATION_ID}'
    url_param_only: true
    required: true
    immutable: true
  - !ruby/object:Api::Type::String
    name: serviceId
    description: 'The Service identifier.'
    url_param_only: true
    required: true
    immutable: true
properties:
  - !ruby/object:Api::Type::String
    name: name
    output: true
    description: "Identifier. The resource name of a Service. Format:\n\"projects/{host-project-id}/locations/{location}/applications/{application-id}/services/{service-id}\""
  - !ruby/object:Api::Type::String
    name: displayName
    description: 'User-defined name for the Service.'
  - !ruby/object:Api::Type::String
    name: description
    description: 'User-defined description of a Service.'
  - !ruby/object:Api::Type::NestedObject
    output: true
    name: serviceReference
    description: 'Reference to an underlying networking resource that can comprise a
      Service.'
    properties:
      - !ruby/object:Api::Type::String
        name: uri
        description: "Output only. The underlying resource URI (For example, URI of Forwarding
          Rule, URL Map,\nand Backend Service)."
        output: true
  - !ruby/object:Api::Type::NestedObject
    output: true
    name: serviceProperties
    description: 'Properties of an underlying cloud resource that can comprise a Service.'
    properties:
      - !ruby/object:Api::Type::String
        name: gcpProject
        description: "Output only. The service project identifier that the underlying
          cloud resource resides in."
        output: true
      - !ruby/object:Api::Type::String
        name: location
        description: "Output only. The location that the underlying resource resides in,
          for example, us-west1."
        output: true
      - !ruby/object:Api::Type::String
        name: zone
        description: "Output only. The location that the underlying resource resides in
          if it is zonal, for example, us-west1-a)."
        output: true
  - !ruby/object:Api::Type::NestedObject
    name: attributes
    description: 'Consumer provided attributes.'
    properties:
      - !ruby/object:Api::Type::NestedObject
        name: criticality
        description: 'Criticality of the Application, Service, or Workload'
        properties:
          - !ruby/object:Api::Type::Enum
            name: type
            description: 'Criticality type.'
            required: true
            values:
              - :MISSION_CRITICAL
              - :HIGH
              - :MEDIUM
              - :LOW
      - !ruby/object:Api::Type::NestedObject
        name: environment
        description: 'Environment of the Application, Service, or Workload'
        properties:
          - !ruby/object:Api::Type::Enum
            name: type
            description: 'Environment type.'
            required: true
            values:
              - :PRODUCTION
              - :STAGING
              - :TEST
              - :DEVELOPMENT
      - !ruby/object:Api::Type::Array
        name: developerOwners
        description: 'Developer team that owns development and coding.'
        item_type: !ruby/object:Api::Type::NestedObject
          properties:
            - !ruby/object:Api::Type::String
              name: displayName
              description: 'Contact''s name.'
            - !ruby/object:Api::Type::String
              name: email
              description: 'Required. Email address of the contacts.'
              required: true
      - !ruby/object:Api::Type::Array
        name: operatorOwners
        description: 'Operator team that ensures runtime and operations.'
        item_type: !ruby/object:Api::Type::NestedObject
          properties:
            - !ruby/object:Api::Type::String
              name: displayName
              description: 'Contact''s name.'
            - !ruby/object:Api::Type::String
              name: email
              description: 'Required. Email address of the contacts.'
              required: true
      - !ruby/object:Api::Type::Array
        name: businessOwners
        description: 'Business team that ensures user needs are met and value
          is delivered'
        item_type: !ruby/object:Api::Type::NestedObject
          properties:
            - !ruby/object:Api::Type::String
              name: displayName
              description: 'Contact''s name.'
            - !ruby/object:Api::Type::String
              name: email
              description: 'Required. Email address of the contacts.'
              required: true
  - !ruby/object:Api::Type::String
    name: discoveredService
    diff_suppress_func: 'tpgresource.ProjectNumberDiffSuppress'
    description: 'Immutable. The resource name of the original discovered
      service.'
    required: true
    immutable: true
  - !ruby/object:Api::Type::String
    name: createTime
    description: 'Output only. Create time.'
    output: true
  - !ruby/object:Api::Type::String
    name: updateTime
    description: 'Output only. Update time.'
    output: true
  - !ruby/object:Api::Type::String
    name: uid
    description: "Output only. A universally unique identifier (UUID) for the `Service`
      in the UUID4\nformat."
    output: true
  - !ruby/object:Api::Type::String
    name: state
    description: "Output only. Service state. Possible values: STATE_UNSPECIFIED CREATING ACTIVE DELETING DETACHED"
    output: true
