name: magic-modules

permissions: read-all

on:
  pull_request:

jobs:
  lint-yaml:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: repo
          fetch-depth: 0
      - name: Check for mmv1 product file changes
        id: pull_request
        run: |
          cd repo
          git config user.name "modular-magician"
          git config user.email "magic-modules@google.com"
          git fetch origin ${{ github.base_ref }} # Fetch the base branch
          git merge --no-ff origin/${{ github.base_ref }} # Merge with the base branch
          yamlfiles=$(git diff --name-only origin/${{ github.base_ref }} -- mmv1/products) # Compare with the base branch
          if [ ! -z "$yamlfiles" ]; then
            echo "yamlfiles=repo/${yamlfiles//$'\n'/ repo/}" >> $GITHUB_OUTPUT
          fi
      - name: Install yamllint
        if: ${{ !failure() && steps.pull_request.outputs.yamlfiles != '' }}
        run: pip install yamllint
      - name: Lint YAML files
        if: ${{ !failure() && steps.pull_request.outputs.yamlfiles != '' }}
        run: yamllint -c repo/.yamllint ${{steps.pull_request.outputs.yamlfiles}}
  rake-tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: repo
          fetch-depth: 2
      - name: Merge base branch
        id: pull_request
        run: |
          cd repo
          git config user.name "modular-magician"
          git config user.email "magic-modules@google.com"
          git fetch origin ${{ github.base_ref }} # Fetch the base branch
          git merge --no-ff origin/${{ github.base_ref }} # Merge with the base branch
      - name: Set up Ruby
        uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
        with:
          ruby-version: '3.1'
      - name: Install dependencies
        run: |
          cd repo/mmv1
          bundle install
      - name: Run rake tests
        run: |
          cd repo/mmv1
          bundle exec rake test

