name: membership-checker

permissions: read-all

on:
  pull_request:
    paths:
      - '.ci/magician/**'

jobs:
  build-and-unit-tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.21'
      - name: Run membership checker unit tests
        run: |
          cd .ci/magician
          go test ./... -v
