name: TeamCity Services Diff Check
permissions: read-all

on:
  workflow_dispatch:
  pull_request:
    types: [opened, edited]
    paths:
      - '.github/workflows/teamcity-services-diff-check.yml'
      - 'mmv1/third_party/terraform/.teamcity/components/inputs/services_ga.kt'
      - 'mmv1/third_party/terraform/.teamcity/components/inputs/services_beta.kt'
jobs:
  check-pr:
    runs-on: ubuntu-22.04
    steps:
      - name: Check for New Services
        run: |
          newServices=$(($(git diff --name-only --diff-filter=A origin/main HEAD | grep "mmv1/products" | wc -l)))
          if [ "$newServices" != "0" ];then
          exit 1
          fi
  terraform-provider-google:
    uses: ./.github/workflows/build-downstream.yml
    with:
      repo: 'terraform-provider-google'
      
  terraform-provider-google-beta:
      uses: ./.github/workflows/build-downstream.yml
      with:
        repo: 'terraform-provider-google-beta'
      
  teamcity-services-diff-check:
    needs: [terraform-provider-google, terraform-provider-google-beta]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      
      - name: Download built artifacts
        uses: actions/download-artifact@v2
        with:
          name: artifact-terraform-provider-google
          path: artifacts
      
      - name: Unzip the artifacts and delete the zip
        run: |
          unzip -o artifacts/output.zip -d ./provider
          rm artifacts/output.zip

      - name: Download built artifacts
        uses: actions/download-artifact@v2
        with:
          name: artifact-terraform-provider-google-beta
          path: artifacts
  
      - name: Unzip the artifacts and delete the zip
        run: |
          unzip -o artifacts/output.zip -d ./provider
          rm artifacts/output.zip

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.20'

      - name: Cache Go modules and build cache
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-test-terraform-provider-google-${{hashFiles('go.sum','google-*/transport/**','google-*/tpgresource/**','google-*/acctest/**','google-*/envvar/**','google-*/sweeper/**','google-*/verify/**') }}
          restore-keys: |
              ${{ runner.os }}-test-terraform-provider-google-${{ hashFiles('go.sum') }}
              ${{ runner.os }}-test-terraform-provider-google-

      - name: Diff Check
        run: |
          cd tools/teamcity-diff-check
          go run main.go
          go run main.go -provider=google-beta -service_file=services_beta.kt

          