name: unit-tests-diff-processor

permissions: read-all

on:
  pull_request:
    paths:
      - 'tools/diff-processor/**'

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.21.0'

      - name: Build
        run: |
          cd tools/diff-processor
          make clone OWNER_REPO=hashicorp/terraform-provider-google DEPTH=1
          make build OLD_REF=main NEW_REF=main

      - name: Test
        run: |
          cd tools/diff-processor
          go test -v ./...
