name: unit-test-tpg
permissions: read-all

on:
  workflow_call:
    inputs:
      repo:
        description: 'Repository for the matrix'
        required: true
        type: string

jobs:
  compile-and-unit-tests:
    name: unit-test-${{ inputs.repo }}
    runs-on: ubuntu-22.04
    steps:
      - name: Download built artifacts
        uses: actions/download-artifact@v2
        with:
          name: artifact-${{ inputs.repo }}
          path: artifacts

      - name: Unzip the artifacts and delete the zip
        run: |
          unzip artifacts/output.zip -d ./
          rm artifacts/output.zip

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.20'

      - name: Build Provider
        run: |
          go build

      - name: Run Unit Tests
        run: |
          make testnolint

      - name: Lint Check
        run: |
          make lint

      - name: Documentation Check
        run: |
          make docscheck
